# Site settings
title: TriComp
email: tricomp@ens-lyon.fr
description: > # this means to ignore newlines until "baseurl:"
  TriComp est un compilateur de tricot.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tricomp.github.io/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  TriComp

# Build settings
markdown: kramdown
